### ISSUE TITLE
Intro state

### ISSUE THREAD

**Issue by mschober** [Rushwind13/JMoria#37]
GIVEN I start the game
THEN I enter STATE_INTRO
AND The intro page is displayed

and

GIVEN I am in STATE_INTRO
WHEN I press the spacebar
THEN I am now in STATE_RUNNING (or whatever this is called)

AC:
* Add STATE_INTRO to the valid game states
* STATE_INTRO should happen after title screen, character creation, and before town creation / dungeon creation, spawning anything
* STATE_INTRO should have its own MessagesDT

Notes:
* this is done a lot, here's a famous one from another roguelike https://nethackwiki.com/wiki/Introduction
* It's not hard to do. There is even a "TOMBSTONE" mode that brings up "modal dialogs" -- just need to throw the game into (a new) "INTRO" state with appropriate IntroDT
* all the new states (title, character creation, intro) can be added piecemeal without breaking anything, the whole game runs in a State machine.

_Originally posted by @Rushwind13 in https://github.com/Rushwind13/JMoria/pull/35#discussion_r1807979207_

**Comment by Rushwind13** [comment]
https://github.com/Rushwind13/JMoria/pull/108
