### ISSUE TITLE
Monster attack effects crash game

### ISSUE THREAD

**Issue by Rushwind13** [Rushwind13/JMoria#91]
[INFO]: Red Jelly choosing attack: MON_FLAG_SPORE
[INFO]: Red Jelly rolled: 64.56
[INFO]: Red Jelly did 0.00 damage (rolled <EFFECT_FLAG_FIRE)(damagemult: 1.00). [INFO]: Remaining HP: 9.76
Abort trap: 6

the error is that the file parsing for attack is messed up, and we are now trying to actually use the flavors. This is a config bug in Items.txt and will need to be fixed via watching FileParse carefully

Also, this is preventing worm mass crawl from doing damage

**Comment by Rushwind13** [comment]
Read file has bugs in monster attack and item effect, refactor was never completed.

**Comment by mschober** [comment]
Here's another example:
[INFO]: Green Jelly did 0.00 damage (rolled <EFFECT_FLAG_ACID)(damagemult: 1.00). [INFO]: Remaining HP: 3.86

**Comment by Rushwind13** [comment]
https://github.com/Rushwind13/JMoria/pull/95

There may still be an existing bug because of double-AIMgr->Update()
